title: Nazrin's portfolio
author: Pengiran Nazrin
description: A simple site to showcase the work of Pengiran Nazrin
remote_theme: pages-themes/architect@v0.2.0
repository: Nazisagit/Nazisagit.github.io

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
